# Generated by Django 6.1 on 2026-09-08 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebook',
            name='member',
        ),
        migrations.AddField(
            model_name='issuebook',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_app.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
