# Generated by Django 6.1 on 2026-09-16 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_remove_issuebook_member_issuebook_user_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRequest',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.user')),
            ],
        ),
    ]
